updated to solr 1.4 with LocalSolr embedded

diff --git a/solr/solr/bin/snapinstaller b/solr/solr/bin/snapinstaller
--- a/solr/solr/bin/snapinstaller
+++ b/solr/solr/bin/snapinstaller
@@ -30,6 +30,10 @@ unset master_host master_status_dir data_dir user verbose debug
 prog=${0##*/}
 log=${solr_root}/logs/${prog}.log
 
+LOCKDIR="${solr_root}/logs/snapinstaller-lock"
+PIDFILE="${LOCKDIR}/PID"
+
+
 # define usage string
 USAGE="\
 usage: $prog [-M master] [-S sdir] [-d dir] [-u username] [-v]
@@ -104,13 +108,27 @@ then
     master_status_dir=${solr_root}/${master_status_dir}
 fi
 
-start=`date +"%s"`
+setStartTime
+
+if test -r $PIDFILE
+then
+  OTHERPID="$(cat "${PIDFILE}")"
+  if ! kill -0 $OTHERPID &>/dev/null; then
+    logMessage removing stale lock ${OTHERPID}
+    rm -rf "${LOCKDIR}"
+  else
+    logExit "lock failed, PID ${OTHERPID} is active" 1
+  fi
+fi
+
+mkdir "${LOCKDIR}" &>/dev/null
+echo "$$" >"${PIDFILE}"
 
 logMessage started by $oldwhoami
 logMessage command: $0 $@
 
 # get directory name of latest snapshot
-name=`ls ${data_dir}|grep 'snapshot\.'|grep -v wip|sort -r|head -1`
+name=`perl -e 'chdir q|'${data_dir}'|; print ((sort grep {/^snapshot[.][1-9][0-9]{13}$/} <*>)[-1])'`
 
 # clean up after INT/TERM
 trap 'echo "caught INT/TERM, exiting now but partial installation may have already occured";/bin/rm -rf ${data_dir"/index.tmp$$;logExit aborted 13' INT TERM
@@ -141,9 +159,20 @@ fi
 # install using hard links into temporary directory
 # remove original index and then atomically copy new one into place
 logMessage installing snapshot ${name}
-cp -lr ${name}/ ${data_dir}/index.tmp$$
-/bin/rm -rf ${data_dir}/index
-mv -f ${data_dir}/index.tmp$$ ${data_dir}/index
+if [[ "${OS}" == "SunOS" || "${OS}" == "Darwin" || "${OS}" == "FreeBSD" ]]
+then
+  orig_dir=$(pwd)
+  mkdir ${data_dir}/index.tmp$$ && \
+  cd ${name} && \
+  find . -print|cpio -pdlmu ${data_dir}/index.tmp$$ 1>/dev/null 2>&1 && \
+  /bin/rm -rf ${data_dir}/index && \
+  mv -f ${data_dir}/index.tmp$$ ${data_dir}/index
+  cd ${orig_dir}
+else
+  cp -lr ${name}/ ${data_dir}/index.tmp$$ && \
+  /bin/rm -rf ${data_dir}/index && \
+  mv -f ${data_dir}/index.tmp$$ ${data_dir}/index
+fi
 
 # update distribution stats
 echo ${name} > ${solr_root}/logs/snapshot.current
@@ -165,4 +194,5 @@ then
   logExit failed 1
 fi
 
+rm -rf "${LOCKDIR}"
 logExit ended 0
